version: "3.9"

services:
  eureka-server:
    build: ./eureka-server
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    ports:
      - "8761:8761"     # muốn kín nội bộ thì bỏ dòng này
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 3s
      retries: 12
    restart: unless-stopped

  quiz-user-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASS}
    volumes:
      - user_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  quiz-auth-service:
    build: ./quiz-auth-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      # quan trọng: dùng hostname 'eureka-server' thay vì localhost
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    depends_on:
      eureka-server:
        condition: service_healthy
      quiz-user-service:
        condition: service_healthy
    restart: unless-stopped

  quiz-user-service:
    build: ./quiz-user-service
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      DB_HOST: ${USER_DB_HOST}
      DB_PORT: ${USER_DB_PORT}
      DB_NAME: ${USER_DB_NAME}
      DB_USER: ${USER_DB_USER}
      DB_PASS: ${USER_DB_PASS}
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:9002/actuator/health"]
      interval: 10s
      timeout: 5s
      start_period: 40s
      retries: 12

    depends_on:
      eureka-server:
        condition: service_healthy
      quiz-user-db:
        condition: service_healthy
    restart: unless-stopped

  api-gateway:
    build: ./api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
      quiz-auth-service:
        condition: service_started
      quiz-user-service:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  user_pgdata:
