spring:
  application.name: quiz-user-service
  profiles.active: ${SPRING_PROFILES_ACTIVE:dev}

eureka.client.serviceUrl.defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# --- dev ---
---
spring:
  config.activate.on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quiz_user_db}
    username: ${DB_USER:user_user}
    password: ${DB_PASS:user_pass}
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true

# --- docker ---
---
spring:
  config.activate.on-profile: docker
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:quiz_user_db}
    username: ${DB_USER:user_user}
    password: ${DB_PASS:user_pass}
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
server:
  port: 9002
# --- prod ---

---
spring:
  config.activate.on-profile: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:quiz-user-db}:${DB_PORT:5432}/${DB_NAME:quiz_user_db}
    username: ${DB_USER:user_user}
    password: ${DB_PASS:user_pass}
  jpa:
    hibernate.ddl-auto: none
