server:
  port: 8080

spring:
  application.name: api-gateway
  main.web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: quiz-auth-service
          uri: lb://quiz-auth-service
          predicates:
            - Path=/auth/**
        - id: quiz-user-service
          uri: lb://quiz-user-service
          predicates:
            - Path=/users/**
eureka.client.serviceUrl.defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
jwt:
  secret:
    ${JWT_SECRET}
