spring:
  application.name: quiz-auth-service
  profiles.active: ${SPRING_PROFILES_ACTIVE:dev}

eureka.client.serviceUrl.defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

# --- dev ---
---
spring:
  config.activate.on-profile: dev


# --- docker ---
---
spring:
  config.activate.on-profile: docker
server:
  port: 9001
jwt:
  secret:
    ${JWT_SECRET}
  expiration:
    ${JWT_EXPIRATION}
# --- prod ---
---
spring:
  config.activate.on-profile: prod

